### ISSUE TITLE
Automatic question paper generator

### ISSUE THREAD

**Issue by srilakshmi1986** [Chiragmodi1247/question-paper-generator#1]
hi thanks for your contribution on this iam working on the same one unable to execute the code
Errors are : 500 error internal server error and also favicon.ico

**Comment by srilakshmi1986** [comment]
![Uploading Screenshot 2022-10-26 160134.jpg…]()

**Comment by srilakshmi1986** [comment]
(node:14808) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-warnings ...` to show where the warning was created)
Server is live at Port: 3000
C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\topologies\server.js:441
          new MongoNetworkError(
          ^

MongoNetworkError: failed to connect to server [ds119606.mlab.com:19606] on first connect [Error: getaddrinfo ENOTFOUND ds119606.mlab.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\topologies\server.js:441:11)
    at Pool.emit (node:events:513:28)
    at C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\pool.js:564:14
    at C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\pool.js:1000:11
    at C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\connect.js:32:7
    at callback (C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\connect.js:300:5)
    at Socket.<anonymous> (C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\connect.js:330:7)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[nodemon] app crashed - waiting for file changes before starting...
PS C:\Users\REGULA SRILAKSHMI\question-paper-generator-master> node app.js            
{
  PORT: '3000',
  DATABASEURL: 'mongodb://saif:saif123@ds119606.mlab.com:19606/sen'
}
(node:8032) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-warnings ...` to show where the warning was created)
Server is live at Port: 3000
C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\topologies\server.js:441
          new MongoNetworkError(
          ^

MongoNetworkError: failed to connect to server [ds119606.mlab.com:19606] on first connect [Error: getaddrinfo ENOTFOUND ds119606.mlab.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\topologies\server.js:441:11)
    at Pool.emit (node:events:513:28)
    at C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\pool.js:564:14
    at C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\pool.js:1000:11
    at C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\connect.js:32:7
    at callback (C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\connect.js:300:5)
    at Socket.<anonymous> (C:\Users\REGULA SRILAKSHMI\question-paper-generator-master\node_modules\mongodb\lib\core\connection\connect.js:330:7)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by srilakshmi1986** [comment]
DATABASEURL = mongodb://saif:saif123@ds119606.mlab.com:19606/sen
